### ISSUE TITLE
As a user, I want to know what prerequisites have to be met so a chart can be rendered

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#101]
Example: I opened the million dollar homes sample notebook. Visualization wasn't working because

1. I was using an unsupported browser

1. I didn't know that for mapbox the chart options need to be customized (an access token must be provided)

1. I didn't know where to obtain the token

**Comment by rajrsingh** [comment]
Mapbox token requirement described better with inline help https://github.com/ibm-cds-labs/pixiedust/commit/8294ee54cdcdc88086e6721626fec9c51edfbd41. No browser is unsupported. Please open another issue if you feel a certain browser won't work.
