### ISSUE TITLE
display(): "Download SVG" doesn't work

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#104]
I've tried Chrome and Safari on Mac.

**Comment by rajrsingh** [comment]
@ptitzler for which renderers?

**Comment by ptitzler** [comment]
Sorry, for both line chart renderers. It's working for pies etc. I assumed (incorrectly I guess) that this option is not chart type specific.

**Comment by MargrietGroenendijk** [comment]
I am getting the same error, nothing happens when I try to `Download SVG` of a bar chart

**Comment by chetnawarade** [comment]
@DTAIEB @vabarbosa in **FF Debugger** there is an exception happening in file:

 pixiedust/pixiedust/display/chart/renderers/templates/chartHeader.html line:

`var svg = $("#wrapperHTML{{prefix}} svg.mpld3-figure")[0].outerHTML;`

fileName: "http://localhost:8888/static/notebook/js/main.min.js?v=e80a0ad9bee7ad0d5865624902d5405d line 87 > eval"
lineName: 348
message:"$(...)[0] is undefined"
__proto__:TypeError 

**Chrome Developer Tools** catches this:
Uncaught TypeError: Cannot read property 'outerHTML' of undefined
    at HTMLButtonElement.eval (eval at globalEval (jquery.min.js:4), <anonymous>:348:60)
    at HTMLButtonElement.dispatch (jquery.min.js:5)
    at HTMLButtonElement.y.handle (jquery.min.js:5)

looks like the same file min.js that's throwing up on $()[0], should we check before calling 'outerHTML'? other ideas?

**Comment by chetnawarade** [comment]
^ issue happens in a new cell

**Comment by DTAIEB** [comment]
@chetnawarade Is it happening when mpld3 is actually being used?

**Comment by chetnawarade** [comment]
@DTAIEB can't tell, maybe. When i read .ipynb that are checked in under/tests for example, it has tons of html in it which has lots of wrapperHTMLxxxxxxx in:

```
"outputs": [
    {
     "data": {
      "text/html": [ ..........
```

Now in the notebook (or under tests or new) that i am constantly restarting kernel, creating new cells lot of ^ html code is simply missing that probably implies script functions didn't complete because of the exception above or mpld3 calls not being made or something else, still catching up with the html code generation. i remember Download working in old arch and it still works on cells under /tests/*.ipynb.

Size of new notebooks are 24KB (532 lines), the ones under /tests are 124KB (5842 lines) - html code is missing from new ones.

**Comment by chetnawarade** [comment]
@DTAIEB @vabarbosa puzzled as in a new notebook below are missing still Options dialog work but not 'Download SVG' can't figure where is mapOptionsxxxx living? in memory instead of .ipynb?

`"<script>\n",
       "$(\"#mapOptions91b8fed3\").click(function(){\n",
       "    \n",
       "    var globalNested={}\n",
       "require(['base/js/dialog'],function(dialog){\n",
       "        var modal = dialog.modal;\n",
       "        var options = {\n",
       "            title: \"Pixiedust: Chart Options\",\n",`

Is this architecture change?

**Comment by DTAIEB** [comment]
@chetnawarade this code was written before renderers, we need to enable download only when renderer is matplotlib and mpld3 is enabled.

**Comment by DTAIEB** [comment]
Fix provided in PR #162

**Comment by ptitzler** [comment]
Why would data download be dependent on the renderer?

**Comment by DTAIEB** [comment]
This download is specific for SVG generated by mpld3 which is only available in matplotlib renderer. For matplotlib chart rendered without mpld3 i.e static png, users can always right click on the browser to download the image. 
Bokeh provides it's own way of downloading the image.
