### ISSUE TITLE
display(): Options > "# of rows to display" shouldn't accept 0 as valid input

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#105]

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/pull/125/commits/8bf3875f8793879210bb4853a79da8c03f8e8a04
OK button is disabled if row is set to 0

**Comment by vabarbosa** [comment]
@ptitzler please review, test, and close if satisfactory

**Comment by ptitzler** [comment]
@vabarbosa Could you also reject negative input values? Not sure what the behavior was in older PD versions but now `-2` is accepted as an input.

**Comment by vabarbosa** [comment]
negative values addressed in https://github.com/ibm-cds-labs/pixiedust/commit/b2dc3dbbb3b781426a0368db161ddeeb845793f9
@ptitzler please review latest update. thx

**Comment by ptitzler** [comment]
:+1:
