### ISSUE TITLE
display(): options > "values" should require at least one field

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#106]
It's currently possible to only specify a key (but no value) in the options. I can't think of a scenario where this kind of setting would result in a useful chart. Can you?

**Comment by rajrsingh** [comment]
don't think you meant to label this "blog" ;)

**Comment by rajrsingh** [comment]
There is a very basic use case for mapping -- just show all the locations of the data without coloring it in any way -- but I wouldn't be upset if value was required

**Comment by ptitzler** [comment]
That one makes sense, but then this exception case should be handled for other chart types. And you are right about `blog` vs `bug`. Thanks for fixing my defect. I have validated that the correct label is now applied :smiley:

**Comment by ptitzler** [comment]
Looks okay in 0.89
