### ISSUE TITLE
display(): Stash to Cloudant fails with ClassNotFoundException 

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#108]
1. Create a valid connection profile
2. Stash to Cloudant results in 

`ClassNotFoundException: Failed to find data source: com.cloudant.spark`

**Comment by DTAIEB** [comment]
@chetnawarade delivered a fix today in PR # #149

**Comment by ptitzler** [comment]
The error message does not provide sufficient information because a user wouldn't necessarily know where to find `cloudant-spark.jar` (it doesn't seem to be in the standard install binaries). In general all dependencies should be pre-installed and configured if an option is displayed.

**Comment by chetnawarade** [comment]
If the cloudant-spark jar is missing then below message is displayed, if user clicks on the url information about manual one-time setup are available

`Please setup one time manual steps to configure stashing to Cloudant database at https://ibm-cds-labs.github.io/pixiedust/install.html#stash-to-cloudant`

@ptitzler please review and consider for 1.0 go/no go.

**Comment by chetnawarade** [comment]
Closing per go/no-go meeting.
