### ISSUE TITLE
Line/Bar Chart - Impossible to have 2 lines / 2 bars?

### ISSUE THREAD

**Issue by hatv** [ibm-cds-labs/pixiedust#11]
I have a dataframe with column A, B and C.
I want A to be the x-axis.
I want B to be the size of the bar or the height of the line.
I want C to be the category, to have an other bar or an other line for each C attribute with a different color.

From the options of PixieDust, I can see the "keys" and "values" but I see nothing for the categories.

**Comment by DTAIEB** [comment]
@hatv can you look at the latest version (0.81) that support bar chart grouping, and let us know if that answer your question. If not, can you give us a detailed example with data.

Here is a screen shot of the latest version bar chart grouping:

![image](https://cloud.githubusercontent.com/assets/4912140/23038397/e3c38ee0-f457-11e6-8cdf-1de76124bb37.png)

**Comment by hatv** [comment]
Simple example:

    d1 = sqlContext.createDataFrame(
    [(2010, 'Camping Equipment', 3),
    (2010, 'Golf Equipment', 1),
    (2010, 'Mountaineering Equipment', 1),
    (2010, 'Outdoor Protection', 2),
    (2010, 'Personal Accessories', 2),
    (2011, 'Camping Equipment', 4),
    (2011, 'Golf Equipment', 5),
    (2011, 'Mountaineering Equipment',2),
    (2011, 'Outdoor Protection', 4),
    (2011, 'Personal Accessories', 2),
    (2012, 'Camping Equipment', 5),
    (2012, 'Golf Equipment', 5),
    (2012, 'Mountaineering Equipment', 3),
    (2012, 'Outdoor Protection', 5),
    (2012, 'Personal Accessories', 3),
    (2013, 'Camping Equipment', 8),
    (2013, 'Golf Equipment', 5),
    (2013, 'Mountaineering Equipment', 3),
    (2013, 'Outdoor Protection', 8),
    (2013, 'Personal Accessories', 4)],
    ["year","category","customers"])

    display(d1)`

Let's say last number is number of customers per year that I want to draw with line chart.
Obviously I want a different line per category but what I got is
![image](https://cloud.githubusercontent.com/assets/2877005/23073781/e0748840-f536-11e6-89cb-8a44933740d1.png)

And from the options, there is no way to define a Group or Category, only Keys and Values.
Bar chart and line chart interpret having 2 columns as keys in different ways :
- with bar chart, the first key is x-axis, the second key is bar/color
- with line chart, the first key is x-axis, the second is x-axis also

Either map the Tableau Software way like in the bar chart method (automatic) or let users define a grouping key but that option may vary depending on the visualization type.

**Comment by DTAIEB** [comment]
@hatv Following changes were made that hopefully address this valid requirement:
For bar and line charts, a new "Categorize by" combo box option appears on the right of the chart. User can choose a column that will be use as a group series categorization:

1. No categorization:
![image](https://cloud.githubusercontent.com/assets/4912140/23148181/22f2a710-f7b2-11e6-8254-3c1fbb4b87b4.png)

2. Categorize by year, grouped:
![image](https://cloud.githubusercontent.com/assets/4912140/23148204/4b942b58-f7b2-11e6-862a-c34bd61e5cef.png)

3. Categorize by year, stacked:
![image](https://cloud.githubusercontent.com/assets/4912140/23148224/5f5334f4-f7b2-11e6-93e7-351c98047b41.png)

4. Categorize by year, subplots:
![image](https://cloud.githubusercontent.com/assets/4912140/23148240/73c89b72-f7b2-11e6-8dda-be8b0afb0644.png)

I still need to polish for edge values, but would appreciate your feedback. You can get these updated from Pypi, PixieDust v 0.82

cc/ @jessmantaro

**Comment by hatv** [comment]
That's good! Except I don't understand why some options are in the "options" menu while others are displayed in the right pane

**Comment by DTAIEB** [comment]
Yeah, the design still needs to be adjusted, but basically we want to have only the key/value selections from columns in the options dialog since it takes a lot of real estate and have every other dynamic options in the right pane
