### ISSUE TITLE
display(): options > problem displaying more than 3+ fields

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#111]
If a data set contains more than six fields (see million dollar home sales sample) it's not possible to 
choose from all available fields in "fields". Only 6 are displayed and the rest is truncated and cannot be selected. If more than 3 fields are selected as "keys" or "values" only 3 are displayed. Reason: no scroll bars.

**Comment by vabarbosa** [comment]
@ptitzler scroll bars are present for me:

<img width="696" alt="screen shot 2017-02-16 at 3 45 54 pm" src="https://cloud.githubusercontent.com/assets/13156555/23040400/2c5cf270-f45f-11e6-836a-a13c8f5a6749.png">

if you are using a mac you may want to verify your **System Preferences... > General > Show scroll bars** settings

**Comment by ptitzler** [comment]
:+1:
