### ISSUE TITLE
display() - line chart / matplotlib / "log scale on y" hides grid lines

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#112]
```
import pixiedust
df = pixiedust.sampleData(6)
display(df)
```
* Select line chart 
* Select _Options_ > _Keys_: `STATE`
* Select _Options_ > _Values_: `PRICE`
* Select _Options_ > _Aggregation_: `min`

* use  `matplotlib` as renderer. A horizontal grid line is displayed next to each value on the y axis (at 1m, 1.2m, 1.4m, ... up to 2.4m).  

* Check option _log scale on y_. Note that only one line is displayed next to the lowest Y value (10^6 = 1m), but not the other(s) (at 2x10^6 for example) 

If bokeh is used as rendering engine the result looks as expected. Dunno if this is a renderer limitation or something we have control over.

Display is okay if two values are selected, e.g. `PRICE` and `SQFT`.

**Comment by vabarbosa** [comment]
@ptitzler do you have a screenshot and/or data set you are using? i want to make sure i understand.

**Comment by ptitzler** [comment]
I've updated the error description with details.

**Comment by vabarbosa** [comment]
minor gridlines and ticks turned on: https://github.com/ibm-cds-labs/pixiedust/commit/57daed73435d19fb52ff9437dd37054b6237b291
