### ISSUE TITLE
display(): linechart - D3 plotting option for matplotlib breaks visualization

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#113]
1. Use the home sales data set; create the data frame and invoke `display()`. pick `city` as `key` and `price` as `value`. Make no further changes to the options.
1. Choose `matplotlib` as rendering engine. Everything is displayed properly. 
1. Choose the `D3 Rendering (mpld3)` option on the right. At first nothing is displayed. Re-run the cell. In the output cell an error message is displayed "Invalid html output" along with some javascript code.

The line chart is broken from here on. I can visualize the data using other chart types (e.g. pie) but not using the line type.

**Comment by DTAIEB** [comment]
Issue was due to a bug in mpld3 that doesn't know how to deal with locators that are not FixedLocator. I added code to convert to fixedLocators when rendering with mpld3

**Comment by ptitzler** [comment]
:+1:
