### ISSUE TITLE
display()  - general: output cells only display partial information

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#114]
The output cells typically don't provide a scroll bar, often truncating vital information. Load, for example, the home sales sample data set and display it as a table. MAximize the output cell. The output says: `showing 100 of 500` but only a dozen or so rows are displayed. There's no scroll bar displayed ):
I've seen this behavior in several browsers. Not sure if this is pixiedust specific or not ¯\_(ツ)_/¯

**Comment by vabarbosa** [comment]
@ptitzler scrollbars are present for me:

<img width="990" alt="screen shot 2017-02-16 at 3 15 52 pm" src="https://cloud.githubusercontent.com/assets/13156555/23039419/6daf9f42-f45b-11e6-9e0a-85bad9ff99b6.png">

if you are using a mac you may want to verify your **System Preferences... > General > Show scroll bars** settings

**Comment by ptitzler** [comment]
:+1:
