### ISSUE TITLE
Sample notebook "graphFrame with Pixiedust" throws error "You must build Spark with Hive ..."

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#115]
1. Run cell 1. OK (I hope these are read-only credentials?????)
2. Run Cell 2. Error: "You must build Spark with Hive ...."

Should this notebook work without modification?

**Comment by DTAIEB** [comment]
@ptitzler this is a Derby limitation, which happens sometimes when multiple notebooks are running at the same time. Spark 2.0 has addressed this issue, but in the meantime, you can work around it by shutting down all the running notebooks by going to the Running tab and click on shutdown.

![image](https://cloud.githubusercontent.com/assets/4912140/23037865/f20435e2-f455-11e6-844e-c4dd7b6e5cef.png)
