### ISSUE TITLE
Sample data sets containing newline characters cannot be properly loaded using sampleData(n)

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#116]
Impacts example sets:  2 and 5.
It appears that there are no numeric field in this data set according to the schema definition. One would have to perform some data engineering (e.g. convert the `results.X` fields) before any of the `display()` visualizations can be used. It would probably be better for PD to only include data sets that can be used as is out of the box.

**Comment by rajrsingh** [comment]
I don't know why pixiedust is making all the fields strings. In the original CSV file, all the `results.X` fields look numerical to me -- no quotes around the values. Is this a bug with the importer @DTAIEB ?

**Comment by ptitzler** [comment]
The data itself might actually be the root cause. If you look at the airbnb data set data structure `id,listing_url,scrape_id,last_scraped,name,s,...` you'll notice that there are potentially problematic records. Example, record number 2 contains <CRs>, which our parser might not process properly because this record spans multiple rows ?

**Comment by ptitzler** [comment]
Looks like a csv parser issue:

```
$ df=pixiedust.sampleData(2)
$ df.printSchema()
root
 |-- id: string (nullable = true)
...
$ df.select("id").show()
--------------------+
|                  id|
+--------------------+
|You may speak wit...|
|Lyuba is a great ...|
|Please help us he...|
|             1) Name|
|2) Desired check-...|
|(we will do our b...|
|3) Are you flying...|
|Please refer to o...|
|After ten years i...|
|             8249488|
|             8409022|
|             8411173|
```

The csv file is displayed properly in Excel.

**Comment by ptitzler** [comment]
It looks like the loader (load = ShellAccess["sqlContext"].read.format('com.databricks.spark.csv')) in here https://github.com/ibm-cds-labs/pixiedust/blob/master/pixiedust/utils/sampleData.py#L98-L111 can't properly handle newline newline characters in columns. Code needs to be added to replace the newline characters so parsing can be performed without issues.

**Comment by ptitzler** [comment]
@DTAIEB need to delegate to somebody with better Python skills who either fixes the issue or picks other open data sets that don't contain newline characters.

**Comment by rajrsingh** [comment]
@ptitzler, @DTAIEB I did a test removing the `host_about` column and it looks like that was the only troublesome field. Should we take this out and keep the dataset?

**Comment by ptitzler** [comment]
Should be okay for data set 2 as long as we don't anticipate that users would likely want to run text analysis.

**Comment by DTAIEB** [comment]
@rajrsingh @ptitzler this is a known issue with the spark csv connector we are using, see here: https://github.com/databricks/spark-csv/issues/175.

**Comment by rajrsingh** [comment]
resolution: remove AirBnB data set and use the 2 I sent to @DTAIEB today

**Comment by ptitzler** [comment]
@rajrsingh let me know when the data sets have been replaced so I can validate and close the issue.

**Comment by rajrsingh** [comment]
done
https://github.com/ibm-cds-labs/pixiedust/commit/4061381edf77262817f495957b526f1da0774bac
