### ISSUE TITLE
labels of subplots in bar charts with matplotlib are overlapping

### ISSUE THREAD

**Issue by MargrietGroenendijk** [ibm-cds-labs/pixiedust#119]
### Actual behavior
![image](https://cloud.githubusercontent.com/assets/17784157/23027120/403a3b58-f45b-11e6-9dba-0eeaa69d3815.png)

**Comment by MargrietGroenendijk** [comment]
New error when trying this: `numpy.ndarray' object has no attribute 'title` and no chart at all. Works with bokeh

![image](https://cloud.githubusercontent.com/assets/17784157/23471578/bd45e0a2-fea1-11e6-91c1-2d07ecae0cdf.png)

**Comment by vabarbosa** [comment]
@MargrietGroenendijk i am no longer seeing the error you reference: `numpy.ndarray' object has no attribute 'title`
are you still able to reproduce? if so, can you provide the data you are using and the options you are using? thanks
