### ISSUE TITLE
bokeh bar chart error

### ISSUE THREAD

**Issue by MargrietGroenendijk** [ibm-cds-labs/pixiedust#120]
### Expected behavior
I tried with several example datasets to create a Bar Chart with the Bokeh renderer, but this gave the following error in all cases: `'Chart' object has no attribute 'grid'`

**Comment by DTAIEB** [comment]
@MargrietGroenendijk I can't seem to reproduce this issue, can you please include step to reproduce?

**Comment by MargrietGroenendijk** [comment]
@DTAIEB 
* I can make a bar chart with matplotlib and seaborn
* Then I click `bokeh` and get the following error: 'Chart' object has no attribute 'grid'
* Is there a package missing maybe?

**Comment by DTAIEB** [comment]
@MargrietGroenendijk I think the issue is with the version of bokeh that you are using. PixieDust requires at least 0.12 and up. Can you try doing a !pip install --upgrade pixiedust.
I'll add some code to check the version and warn the user.

**Comment by MargrietGroenendijk** [comment]
That worked! Had to use !pip install --upgrade bokeh to make it work

**Comment by thanhpham08** [comment]
I just got the PixieDust notebook v1.1.2. On the cell to display the camping equipments, the matplotlib worked fine. But when changing to Bokeh, it got errors and started to show HTML in output

```

Invalid html output: this._mapping[t[0]] is undefined



<div class="row chart-button-group">
    <div class="form-group col-sm-9" style="padding-right:10px;">
        <button id="mapOptionsa88a1e5f" class="btn btn-default">Options</button>
        
        <button pd_app="pixiedust.apps.gateway.share.ShareChartApp" pd_options="runInDialog=true;title=Share Chart" class="btn btn-default no_loading_msg">Share</button>
    </div>
    
    <div class="form-group col-sm-3">
        <label class="field">Renderer:</label>
        <select class="form-control" id="renderera88a1e5f" style="margin:0; display:inline-block; width:70%;">
            
                <option value="matplotlib" >matplotlib</option>
            
                <option value="bokeh" selected>bokeh</option>
            
        </select>
    </div>
    
</div>

... more
```

**Comment by DTAIEB** [comment]
@thanhpham08 this is a known issue introduced by bokeh since 0.12.7. We were using the charts/bkcharts package which apparently is not supported anymore. We're currently working on a fix which hopefully will be ready soon.
In the meantime, you need to downgrade bokeh to 0.12.6 like so:
!pip install --upgrade bokeh==0.12.6
Restart kernel
Reload page.
