### ISSUE TITLE
As a user handle empty lists gracefully

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#123]
### Expected behavior
Select Histogram, Options dialog should appear but it's not populated as user kept values empty 
### Actual behavior
Options dialog is not populated as user kept values empty 
stack trace attached
### Steps to reproduce the behavior
Select histogram, leave values box empty and click OK, after this action stack trace will be generated and histograms won't be created.
[NoValueSelectionHistogram.txt](https://github.com/ibm-cds-labs/pixiedust/files/781685/NoValueSelectionHistogram.txt)

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/pull/125/commits/8bf3875f8793879210bb4853a79da8c03f8e8a04
OK button is disabled if a list is empty

**Comment by vabarbosa** [comment]
@chetnawarade please review, test, and close if satisfactory

**Comment by chetnawarade** [comment]
+1 thanks @vabarbosa
