### ISSUE TITLE
Plot options before rendering

### ISSUE THREAD

**Issue by gadamc** [ibm-cds-labs/pixiedust#13]
It would be nice to select plotting options before rendering since it can take a while to render large amounts of data. Sitting around waiting for the default behavior to finish before being able to select options. Perhaps a modal window can pop up when you select the chart option before it begins.

**Comment by DTAIEB** [comment]
Yes, I had the same thought and agree with this. @markwatsonatx I think we should simply display the option dialog inline in the cell output area when displaying charts for the first time.

**Comment by DTAIEB** [comment]
This has already been implemented a while ago
