### ISSUE TITLE
Histogram binning

### ISSUE THREAD

**Issue by gadamc** [ibm-cds-labs/pixiedust#14]
I'd like to be able to set histogram bin sizes in some way.

**Comment by DTAIEB** [comment]
@chetnawarade binning has been implemented for matplotlib histogram renderer. Common slider option is in place. Can you please update seaborn and bokeh renderer?

**Comment by chetnawarade** [comment]
@DTAIEB tested bin size slider with bokeh PR #90

**Comment by chetnawarade** [comment]
@gadamc @DTAIEB could we close this issue as we are working on nuances of binning in https://github.com/ibm-cds-labs/pixiedust/issues/135. We are past basics of binning. Please review/close.
