### ISSUE TITLE
display() - legend is not displayed properly for large number of entries

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#146]
```
import pixiedust
df = pixiedust.sampleData(6)
display(df)
```
* Select bar chart (the problem is _not_ specific to the chart type)

* Select _Options_ > _Keys_: `STATE`
* Select _Options_ > _Values_: `SQFT`
* Select _Cluster by_ : `CITY` 

### Actual behavior

Legend scrolls off the display area

**Comment by ptitzler** [comment]
Looking good for bar/bokeh, not so much for bar/mathplotlib.

**Comment by bradley-holt** [comment]
Adding a screenshot as I thought that might be helpful…

<img width="966" alt="pixiedust-146" src="https://cloud.githubusercontent.com/assets/89264/23471804/8fffbd26-fe78-11e6-876d-2fc9df10255b.png">
