### ISSUE TITLE
As a notebook user, I want cleaner pie charts when I have lots of labels

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/pixiedust#152]
### Expected behavior
I'd expect Pixiedust to know if I had lots of overlapping labels that obscure each other and are difficult to read. More specifically, I'd expect Pixiedust to sort the slices so that large chunks and their labels are together, and to collapse the very small slices whose labels would overlap.

### Actual behavior
The slices of the pie chart are not sorted, and ever slice -- no matter how thin -- receives a label. It's so busy that I can't read most of the labels.

### Steps to reproduce the behavior
Load the population data set. Set the key to `Country or Area` and `Year` and `Value` (value here is the actual population). Then, choose the `AVG` aggregation and set the max rows to 1000.

![screen shot 2017-02-22 at 4 36 42 pm](https://cloud.githubusercontent.com/assets/3170980/23233764/deefbc5c-f91d-11e6-8b92-2947174ff6ae.png)

**Comment by DTAIEB** [comment]
@mikebroberg PixieDust will now only keep the top 20 entries in the pie chart and show a message under the chart warning the user.

![image](https://cloud.githubusercontent.com/assets/4912140/23244232/c5480456-f951-11e6-9561-d9783061d97f.png)

Changes are in PR #153

**Comment by mikebroberg** [comment]
Checking!

**Comment by mikebroberg** [comment]
@DTAIEB This is much improved, thanks! However, one bug remains:

The legend in the matplotlib rendering of pie chart is great, and the legend looks good too. But when you choose to display the legend in `D3 Rendering` under pie chart options and choose to `Show legend`, the legend is cut off :(

![screen shot 2017-03-01 at 12 12 37 pm](https://cloud.githubusercontent.com/assets/3170980/23471848/c34e01ec-fe78-11e6-9d66-5292eae6c9be.png)

**Comment by mikebroberg** [comment]
I guess this is a problem with mpld3. So my suggestion would be to disable the option to show a legend for d3 rendering. If that's not possible, then please just close this issue and move it to "DONE". Thanks.

**Comment by DTAIEB** [comment]
@mikebroberg I opted instead to add a warning when using mpld3. We can revisit after 1.0 and decide if we want to keep it
message is:
Warning: While great, D3 rendering is using MPLD3 library which has limitations that have not yet been fixed

**Comment by DTAIEB** [comment]
Fix is in #219
