### ISSUE TITLE
Move Show Legend option out of option dialog and to right pane

### ISSUE THREAD

**Issue by DTAIEB** [ibm-cds-labs/pixiedust#159]
### Expected behavior
For consistency, show legend should always be on the right pane. Move the definition to commonOptions.py
### Actual behavior
Show legend is in the option dialog for some chart types and in the right pane for others.

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/abacbf40f9cb8037d129bf514c54f7363bd5d9e0
