### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by gadamc** [ibm-cds-labs/pixiedust#16]
This might sound a bit nit-picky, but one thing I'd like to see changed would be to avoid using
`from XX import *`, like `from pixidust.display import display` in examples and documentation.   I'm not sure what's in pixiedust (though I could look at the code), but there are probably a lot of modules that potentially have the same names as other graphing packages. Something better might be `import pixiedust.display as pixd` or just use the full path `import pixiedust.diplay`.

It would make it easier for folks to straight copy example code without worrying about namespace collisions. 

Feel free to close this issue if you think I'm being an arse.

**Comment by DTAIEB** [comment]
I don't think it's an issue. A change has been made a while ago that remove the requirement to import display in a Notebook. 
For example:
```
import pixiedust
display(df)
```
