### ISSUE TITLE
google geochart's Markers and Text display options don't seem to work

### ISSUE THREAD

**Issue by jessmantaro** [ibm-cds-labs/pixiedust#163]
Google Map renderer
Got **Regions** display moved setting to work well, but nothing appears when I choose **Markers** and/or **Display**

Using the Total Population by Data set. **Country** in keys, **Value** as Values.  (in Chrome)

**Comment by vabarbosa** [comment]
@jessmantaro @rajrsingh the *markers* and *text* display modes require an API key to function properly. Google map renderer has been updated to allow entry of a Google API key. after obtaining the API key it must be enabled for Google Maps JavaScript API and Geocoding API. once enabled, you may enter it in the renderer's options dialog and the modes should work. if the API is missing the renderer will show a message with appropriate Google support links for getting the API key. let me know if anything is unclear or you need additional info

**Comment by rajrsingh** [comment]
Text size is too small to read and same color as map, and marker color is too close to map

**Comment by rajrsingh** [comment]
Fixed yesterday afternoon
