### ISSUE TITLE
display() barchart / matplotlib / D 3 rendering => color coding missing in legend

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#165]
```
import pixiedust
df = pixiedust.sampleData(6)
display(df)
```
* Select bar chart 

* Select _Options_ > _Keys_: `STATE`
* Select _Options_ > _Values_: `SQFT`
* Select _Cluster by_ : `CITY` 
* Select _Renderer_ > matplotlib
* Select D3 rendering

### Actual behavior

The legend displays N city labels but only one of them has a color assigned to it. The display is fine if D3 rendering is disabled.

**Comment by DTAIEB** [comment]
This is an mpld3 limitation which unfortunately we have no control over. A disclaimer message is now displayed letting the user know that mpld3 should be used with caution.

**Comment by ptitzler** [comment]
In 0.88 got the warning. It's very generic and not that useful. But I can't think of a meaningful way to convey all the limitations that 3rd party dependencies may have so I'll give the fix a :+1:
