### ISSUE TITLE
display() - stash to cloudant doesn't work with official https://github.com/cloudant-labs/spark-cloudant#Binary-download

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#172]
PD 0.8.4: 

I've 
* download https://github.com/cloudant-labs/spark-cloudant/releases/download/v1.6.4/cloudant-spark-v1.6.4-167.jar
* saved it to a temporary directory
* renamed it to `cloudant-spark.jar`
* added `"PYSPARK_SUBMIT_ARGS": "--jars /Users/patti/pixiedust/libs/cloudant-spark.jar --driver-class-path /Users/patti/pixiedust/data/libs/* --master local[10] pyspark-shell",` to the the appropriate kernel.json file
* restarted the notebook/kernel
* loaded sample data

  ```
   import pixiedust
   df = pixiedust.sampleData(6)
   display(df)
  ```

* > stash to Cloudant > create connection ...
* > submit

### Expected behavior

Data is saved success fully

### Actual behavior

Error is raised. The same scenario works with David's older spark-cloudant.jar file.

**Comment by DTAIEB** [comment]
Looks like it's working with cloudant-spark-v1.6.3-125.jar  but not with cloudant-spark-v1.6.4-167.jar

**Comment by DTAIEB** [comment]
Fix to account for behaviour change with saveDBOnSave flag in cloudant-spark-v1.6.4-167.jar. #177

**Comment by ptitzler** [comment]
Works now. Tested with local couchdb installation using the following config
```
{
    "credentials": {
        "username": "myvoice",
        "protocol": "http",
        "url": "http://myvoice:ismypassword@127.0.0.1:5984",
        "host": "127.0.0.1:5984",
        "password": "ismypassword",
        "port": 5984
    },
    "name": "local"

}
```
