### ISSUE TITLE
display() - stash to cloudant: submit button state is invalid

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#173]
PD 0.84: (configured using David's cloudant-spark.jar)

```
import pixiedust
df=pixidiest.sampleData(6)
display(df)
```

* Select _Stash to Cloudant_
* Note that the submit button is disabled
* Create a connection profile (just use the default values)
* Select the connection profile
* Delete the connection profile

### Expected behavior

The _submit_ button is disabled.

### Actual behavior

The _submit_ button is enabled and PD raises exception if the button is clicked: `... unable to find connection ...`

**Comment by DTAIEB** [comment]
Fixed in PR #176

**Comment by ptitzler** [comment]
:+1:
