### ISSUE TITLE
display() - "download as file" accepts negative and 0 row number as input

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#182]
0.85: 
```
import pixiedust
df=pixiedust.sampleData(6)
display(df)
```

* Select _download as file_
* Enter 0 (Zero) or a negative value
* Click *OK*

### Expected behavior

The `OK` button is disabled.

### Actual behavior

The download is started.

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/db9ab8625cfd633630d6ee02b3fcd103c234fa3c

**Comment by ptitzler** [comment]
:+1:
