### ISSUE TITLE
Data format of year wrong in country population example

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/pixiedust#191]
As a `<user type>`, I want to `<task>` so that `<goal>` (make this the title)

### Expected behavior
year is a number
### Actual behavior
year is a string
type: struct
field:
{'metadata': {}, 'type': 'string', 'name': 'Country or Area', 'nullable': True}
{'metadata': {}, 'type': 'string', 'name': 'Year', 'nullable': True}
{'metadata': {}, 'type': 'long', 'name': 'Value', 'nullable': True}
{'metadata': {}, 'type': 'integer', 'name': 'Value Footnotes', 'nullable': True}
### Steps to reproduce the behavior
bokeh - scatterplot - population by country  - set year as key =  error: Column year is not numerical

**Comment by rajrsingh** [comment]
I updated the data set on analytics exchange. Hoping it percolates through to DSX soon

**Comment by DTAIEB** [comment]
@rajrsingh assigning to you as this is an issue with the data set itself. We either want to curate it or remove it altogether.

**Comment by rajrsingh** [comment]
It is fixed in DSX
