### ISSUE TITLE
enableSparkJobProgressMonitor() isn't working on dsx

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#195]
As a user, I want enableSparkJobProgressMonitor() to  enable job monitor report on the cells calling display()

### Expected behavior
<img width="1220" alt="noprogressmonitor" src="https://cloud.githubusercontent.com/assets/12305069/23470617/dda6ceec-fe74-11e6-91f9-4e8988a0d866.png">

### Actual behavior
Job progress monitor isn't displaying

### Steps to reproduce the behavior
Create a new spark instance. Create a new notebook.

!pip install --upgrade --user pixiedust
import pixiedust
pixiedust.enableSparkJobProgressMonitor()
pixiedust.enableJobMonitor()

**Comment by chetnawarade** [comment]
After couple of kernel restarts Job progress monitor is working. 

Keeping this issue open as on local as i see error:

Error Cannot run scala code: SCALA_HOME environment variable not set

**Comment by markwatsonatx** [comment]
I add similar issues with this command running PixieDust on Docker. This may be Docker related, but here is the stacktracke:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/conda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/pixiedust/pixiedust/utils/sparkJobProgressMonitor.py", line 42, in startSparkJobProgressMonitor
    progressMonitor = SparkJobProgressMonitor()
  File "/pixiedust/pixiedust/utils/sparkJobProgressMonitor.py", line 166, in __init__
    self.addSparkListener()
  File "/pixiedust/pixiedust/utils/sparkJobProgressMonitor.py", line 195, in addSparkListener
    _env.getTemplate("sparkJobProgressMonitor/addSparkListener.scala").render()
  File "/opt/conda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2115, in run_cell_magic
    result = fn(magic_arg_s, cell)
  File "<decorator-gen-123>", line 2, in scala
  File "/opt/conda/lib/python2.7/site-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/pixiedust/pixiedust/utils/scalaBridge.py", line 179, in scala
    runnerObject.callMethod("init", pd_getJavaSparkContext(), None if self.hasLineOption(line, "noSqlContext") else self.interactiveVariables.getVar("sqlContext")._ssql_ctx )
  File "/pixiedust/pixiedust/utils/javaBridge.py", line 135, in callMethod
    jMethodParams[i] = None if arg is None else (arg if arg.__class__.__name__ == "JavaClass" else arg.getClass())
  File "/root/spark/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_collections.py", line 228, in __setitem__
    return self.__set_item(key, value)
  File "/root/spark/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_collections.py", line 211, in __set_item
    return get_return_value(answer, self._gateway_client)
  File "/root/spark/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 323, in get_return_value
    format(target_id, ".", name, value))
Py4JError: An error occurred while calling None.None. Trace:
java.lang.NullPointerException
    at py4j.commands.ArrayCommand.convertArgument(ArrayCommand.java:154)
    at py4j.commands.ArrayCommand.setArray(ArrayCommand.java:144)
    at py4j.commands.ArrayCommand.execute(ArrayCommand.java:97)
    at py4j.GatewayConnection.run(GatewayConnection.java:214)
    at java.lang.Thread.run(Thread.java:745)
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/root/spark/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 883, in send_command
    response = connection.send_command(command)
  File "/root/spark/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1040, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
Py4JNetworkError: Error while receiving

**Comment by chetnawarade** [comment]
On DSX: new Spark Instance. New Notebook.

`!pip install --upgrade --user pixiedust `

`Collecting pixiedust
  Downloading pixiedust-0.86.tar.gz (88kB)
    100% |████████████████████████████████| 92kB 5.5MB/s 
Collecting mpld3 (from pixiedust)
  Downloading mpld3-0.3.tar.gz (788kB)
    100% |████████████████████████████████| 798kB 1.4MB/s 
Collecting lxml (from pixiedust)
  Downloading lxml-3.7.3-cp27-cp27m-manylinux1_x86_64.whl (6.8MB)
    100% |████████████████████████████████| 6.8MB 174kB/s 
Building wheels for collected packages: pixiedust, mpld3
  Running setup.py bdist_wheel for pixiedust ... - \ | / - \ | / - \ | done
  Stored in directory: /gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.cache/pip/wheels/5b/e5/66/8b1f0ac86938ee9dabeb7d9830af9020b38e6bb21de01626fb
  Running setup.py bdist_wheel for mpld3 ... - done
  Stored in directory: /gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.cache/pip/wheels/69/bc/68/7ca3b696749d183e998968fc24b0ff3c5e119d9e68bf495b07
Successfully built pixiedust mpld3
Installing collected packages: mpld3, lxml, pixiedust
Successfully installed lxml-3.7.3 mpld3-0.3 pixiedust-0.86`

`import pixiedust`
`Pixiedust database opened successfully
Table VERSION_TRACKER created successfully
 Pixiedust version 0.38
Pixiedust runtime updated. Please restart kernel
Table SPARK_PACKAGES created successfully
Table USER_PREFERENCES created successfully
Table service_connections created successfully`

`pixiedust.enableSparkJobProgressMonitor()`

`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/src/bluemix_jupyter_bundle.v35/notebook/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/src/bluemix_jupyter_bundle.v35/notebook/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 42, in startSparkJobProgressMonitor
    progressMonitor = SparkJobProgressMonitor()
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 166, in __init__
    self.addSparkListener()
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/sparkJobProgressMonitor.py", line 195, in addSparkListener
    _env.getTemplate("sparkJobProgressMonitor/addSparkListener.scala").render()
  File "/usr/local/src/bluemix_jupyter_bundle.v35/notebook/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2120, in run_cell_magic
    result = fn(magic_arg_s, cell)
  File "<decorator-gen-125>", line 2, in scala
  File "/usr/local/src/bluemix_jupyter_bundle.v35/notebook/lib/python2.7/site-packages/IPython/core/magic.py", line 193, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/scalaBridge.py", line 178, in scala
    self.getLineOption(line, "channel"), self.getLineOption(line, "receiver"))
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/javaBridge.py", line 51, in __init__
    self.captureOutput(captureOutput)
  File "/gpfs/fs01/user/sa21-8f355e7c4f46b9-67cce38fb4ab/.local/lib/python2.7/site-packages/pixiedust/utils/javaBridge.py", line 71, in captureOutput
    pixiedustOutputSink = JavaWrapper("com.ibm.pixiedust.PixiedustOutputStream").jHandle(self.outputChannel)
TypeError: 'JavaPackage' object is not callable
`

@DTAIEB i've might have stale database or some leftover, i'll be restarting kernel to see if 0.38 jumps to 0.86

**Comment by chetnawarade** [comment]
Works after a kernel start, pixiedust import shows:

`Pixiedust version upgraded from 0.38 to 0.86`

@DTAIEB this error is limited to small number of users as  very few will upgrade from 0.38 or smaller versions.

@markwatsonatx does look specific to Java virtual machine issue via py4j

```
Py4JError: An error occurred while calling None.None. Trace:
java.lang.NullPointerException
```
^ is happening at the lambda function 

`call = lambda f, *a, **k: f(*a, **k)
File "/pixiedust/pixiedust/utils/scalaBridge.py", line 179, in scala`

wondering if defining function explicitly resolves NPE.

**Comment by markwatsonatx** [comment]
I narrowed my issue down to Spark 2.1 when running locally on Mac or in Docker. Added new issue and added to Icebox: #223

**Comment by chetnawarade** [comment]
Set SCALA_HOME and PATH to /Users/USERNAME/scala-2.10.4 and /Users/USERNAME/scala-2.10.4/bin seeing this error:

`pixiedustRunner.scala:58: error: not found: type PixiedustOutputListener
    def setChannelListener(listener:PixiedustOutputListener){
                                    ^
pixiedustRunner.scala:56: error: not found: type ChannelReceiver
    private val channelReceiver = new ChannelReceiver()
                                      ^
two errors found`

@DTAIEB am i missing something? 

`import pixiedust`
`pixiedust.enableSparkJobProgressMonitor()`

**Comment by chetnawarade** [comment]
LOCAL:

pixiedust.enableJobMonitor() works ok, i see a blue bar progressing when sampleData() is called. Does that indicate enableJobMonitor() worked ok? sampleData is failing while installing

`org.apache.commons:commons-csv:0`

global name 'e' is not defined

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-c22a5dc8901c> in <module>()
      1 pixiedust.installPackage("com.databricks:spark-csv_2.10:1.5.0")
----> 2 pixiedust.installPackage("org.apache.commons:commons-csv:0")

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/packageManager.pyc in installPackage(self, package, base, sc)
     85 
     86             try:
---> 87                 fileLoc=_doDownload(Downloader(base) if base is not None else Downloader())
     88             except RequestException as e:
     89                 #try another base

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/packageManager.pyc in _doDownload(d)
     70                 package=packs[0]
     71                 if not package.version or package.version=='0':
---> 72                     package.version = d.resolver._find_latest_version_available(package)
     73                 fileLoc = package.getFilePath(self.DOWNLOAD_DIR)
     74                 if os.path.isfile(fileLoc):

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/downloader.pyc in _find_latest_version_available(self, package)
     57     def _find_latest_version_available(self, package):
     58         path = "/%s/maven-metadata.xml" % (package.path(False))
---> 59         xml = doRequest(self.base + path, self._onFail, lambda r: self._parseMetadataXML(r))
     60         v = xml.xpath("/metadata/versioning/versions/version[last()]/text()")
     61         if v:

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/downloader.pyc in doRequest(url, onFail, onSuccess, username, password)
     41             onFail(url, e)
     42         else:
---> 43             return onSuccess(response)
     44 
     45 class Resolver(object):

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/downloader.pyc in <lambda>(r)
     57     def _find_latest_version_available(self, package):
     58         path = "/%s/maven-metadata.xml" % (package.path(False))
---> 59         xml = doRequest(self.base + path, self._onFail, lambda r: self._parseMetadataXML(r))
     60         v = xml.xpath("/metadata/versioning/versions/version[last()]/text()")
     61         if v:

/Users/chetnadwarade/pixiedust/pixiedust/packageManager/downloader.pyc in _parseMetadataXML(self, r)
     52         try:
     53             return etree.parse(r)
---> 54         except e:
     55             print(e)
     56 

NameError: global name 'e' is not defined

**Comment by DTAIEB** [comment]
@chetnawarade can you confirm that the error only occurs with Spark 2.1? If so, we should close this issue and keep #223

**Comment by chetnawarade** [comment]
@DTAIEB error happens at the first call after a kernel restart, local progress monitoring not working for display() for both spark 1.6.1 and 2.1.0.

```
pixiedustRunner.scala:58: error: not found: type PixiedustOutputListener
    def setChannelListener(listener:PixiedustOutputListener){
                                    ^
pixiedustRunner.scala:56: error: not found: type ChannelReceiver
    private val channelReceiver = new ChannelReceiver()
                                      ^
two errors found

**Comment by chetnawarade** [comment]
Closing this issue as setup instructions above are done manually. Moving to start using installer so that relevant data/libs have correct pixiedust jars. Error ^ are due to missing pixiedust jars.

**Comment by ulemanstreaming** [comment]
This issue is old and has been closed, but as of today the Spark job monitor still doesn't work in DSX, and enableJobMonitor() still complains about SCALA_HOME not being set. Sure enough, that variable isn't set and I don't know where to set it to avoid the error. %env doesn't do it, nor does setting it in my user's .profile.

DSX 1.2.0.3, Python 2.7 with DSX Spark 2.0.2, Pixiedust 1.1.11 (after install --user --upgrade).

**Comment by vbhat0891** [comment]
Has the issue of SCALA_HOME not being set resolved? Or, is there a workaround for it? I am following the tutorial for Real-time twitter sentiment analysis in a Watson studio notebook. I am running scala code from my python notebook, I get following error in the process.
![image](https://user-images.githubusercontent.com/26983338/48391517-9a39db80-e6cc-11e8-8043-63c030424f6e.png)
