### ISSUE TITLE
Bars in bokeh bar chart do not line up with x-axis labels

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#196]
As a user, I want to view bar charts in bookeh

### Expected behavior

Bars are lined up with x-axis labels

### Actual behavior

Bars are not lined up with x-axis labels

### Steps to reproduce the behavior

Use Boston Crime data
df = pixiedust.sampleData(7)
display(df)
Choose bar chart
Set keys = district
Set values = type
Choose bookeh

See attached screenshot:
<img width="1023" alt="screen shot 2017-03-01 at 10 41 19 am" src="https://cloud.githubusercontent.com/assets/7252838/23470805/01a8eed6-fe6d-11e6-8809-7188ac891148.png">

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/5278f8f7986f35fcaf04c79aaa503b124691b284
