### ISSUE TITLE
Setting scatter plot color to same columns as Value field fails

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#199]
### Expected behavior

I should be able to set the color, the Value field should not be available to select from the pulldown, or a better error message should be displayed.

### Actual behavior

Selecting the Value field results in an error message.

### Steps to reproduce the behavior

Use Boston Crime data
df = pixiedust.sampleData(7)
display(df)
Choose scatter plot
Set keys = X
Set values = Y
Choose bookeh
Set color under Scatter Plot Options to Y

Error Message: 'DataFrame' object has no attribute 'dtype'

**Comment by DTAIEB** [comment]
Fixed in #225
