### ISSUE TITLE
Ensure python 3 compatibility

### ISSUE THREAD

**Issue by esafak** [ibm-cds-labs/pixiedust#2]
I get the following errors upon installation:

``` python
>>> import pixiedust
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/esafak/Library/Python/3.5/lib/python/site-packages/pixiedust/__init__.py", line 19, in <module>
    import packageManager
ImportError: No module named 'packageManager'

>>> from pixiedust.packageManager import PackageManager
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/esafak/Library/Python/3.5/lib/python/site-packages/pixiedust/__init__.py", line 19, in <module>
    import packageManager
ImportError: No module named 'packageManager'
```

I think you have an issue with [relative imports](http://python-future.org/compatible_idioms.html#imports-relative-to-a-package).

**Comment by DTAIEB** [comment]
@esafak Thanks for reporting these issues. We'll take a look asap. Also, feel free to fork and issue a pull request for the one that are easy to fix like the bad indent.
Thanks

**Comment by DTAIEB** [comment]
@esafak PR with support for Python 3.5 has been merge. PixieDust version 0.68 containing this fix has also been uploaded to PyPI. Please let me know if you find any issues.
