### ISSUE TITLE
Histogram only works on numeric values not on strings

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#202]
### Expected behavior
Show a message that histogram (count) isn't supported on string values. Or provide support for this feature

### Actual behavior
Options dialog won't allow the user to proceed if the user selects a string field, its confusing as there is no message, only option is to cancel.

### Steps to reproduce the behavior
Select a string field i.e CITY from pixiedust.sampleData(6).

**Comment by DTAIEB** [comment]
Will be addressed by #204
