### ISSUE TITLE
As anyone, I want to see the data types of each field and acceptable data types of each key or value

### ISSUE THREAD

**Issue by terichadbourne** [ibm-cds-labs/pixiedust#204]
As anyone, I want to see the data types of each field and acceptable data types of each key or value.

### Expected (DESIRED) behavior

As I look at the screen where I set up my display (drag fields to key and value)... 

(a) I would like each field to have a visible indicator of whether it is a string, number, etc.

(b) I would like for "key" and "value" to each be labelled with acceptable data types to drag there (string, number, etc.)

(c) If I try to drag to key or value a field of an unacceptable data type, I'd like it to validate and throw an error if I'm doing something I'm not supposed to do. 

### Actual behavior
 As I drag fields to "key" and "value" fields I don't know what the data type of my field is and whether it's okay to use for the key or value field on this chart type.  If I do something bad, it later throws a message in red says that "Year is not numerical" (or something like that).

### Steps to reproduce the behavior

pick any display type while doing display(df)
click on "options" to get to the screen where you drag fields  to "key" and  "value"

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/834e8b79fb264ac64253d1580731f0e24e731e1c
- each column now has an indicator of the data type (e.g., string, numeric)
- Keys and Values now contain (?) icon that gives additional info about data types accepts
- invalid data types are now prevented from being dropped and warning message is provided
- Fields are now sorted alphabetically
