### ISSUE TITLE
Bokeh bar chart empty when using multiple keys

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#205]
As a user I want to display bar charts using multiple keys

### Expected behavior

Aggregates data based on keys.

### Actual behavior

No data.
Matplotlib shows multiple charts
Pie chart shows a slice per key combo

### Steps to reproduce the behavior

Use Boston Crime data
df = pixiedust.sampleData(7)
display(df)
Choose bar chart
Set keys = district, month
Set values = type
Choose bookeh

**Comment by vabarbosa** [comment]
addressed in https://github.com/ibm-cds-labs/pixiedust/commit/07c4996401747f7de7e01ad9ef319ff5b8147071
