### ISSUE TITLE
display() bar chart > bokeh doesn't render values for large number of data points

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#206]
```
import pixiedust
df=pixiedust.sampleData(2)
display(df)
```

* Select chart type _bar_
* Options > _Keys_: `state`
* Options > _Values_: `price`
* Options > _Aggregation_: `MAX` (problem is not aggregation specific)
* Options > _#rows_: `200`

### Expected behavior

Data values are displayed

### Actual behavior

No data values are displayed (change `#rows` to 10) to see the difference in behavior

**Comment by vabarbosa** [comment]
@ptitzler i am not able to reproduce. there have been multiple updates to bokeh charts so this may have been indirectly fixed. please review and confirm if you are still experiencing this issue.

**Comment by ptitzler** [comment]
Looking good in 0.88.
