### ISSUE TITLE
Bar chart grouped isn't working in bokeh

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#207]
### Expected behavior
Bar chart displaying vertical bars grouped by similar category

### Actual behavior
<img width="1246" alt="barchartnotworkingbokeh" src="https://cloud.githubusercontent.com/assets/12305069/23472113/d52671be-fe79-11e6-92c9-3372cc40262b.png">

### Steps to reproduce the behavior
Cluster by a relevant field, select grouped.

**Comment by vabarbosa** [comment]
@chetnawarade the values you selected produces a very very large number of bars. each bar ends up being so thin you cannot see them. if you use the bokeh zoom tool and zoom in to a specific city you will see the bars. if you try more appropriate values you will bee the grouping:

- **example**
keys: Property Type
values: Beds
cluster by: Price

- **example** 
keys: Property Type
values: Beds
cluster by: Baths
