### ISSUE TITLE
display() map chart: API keys should be retained

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#208]
0.86 (not data set specific)

```
import pixiedust
df=pixiedust.sampleData(2)
display(df)
```

* Select `map` chart type 
* Enter an API key under _options_
* Switch to another chart type
* Select `map` chart type 

### Expected behavior

The API key is retained.

### Actual behavior

The API key needs to be re-entered again.

**Comment by DTAIEB** [comment]
Can't reproduce anymore with the latest code. May have been fixed indirectly.

**Comment by ptitzler** [comment]
No longer reproducable in 0.88. Tested google and mapbox API token.
:+1:
