### ISSUE TITLE
Cluster by value state inconsistency when changing keys in options

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#209]
### Expected behavior

When I add or change keys in options the cluster by value displayed in the UI should match the actual cluster by value being used in the display.

### Actual behavior

When I add or change keys in the options dialog the Cluster by value resets to None, but in some cases is still clustering. In other cases I see an error like so: Ambiguous reference to district. The index names are not unique

### Steps to reproduce the behavior

Use Boston Crime data
df = pixiedust.sampleData(7)
display(df)
Choose bar chart
Set keys = district
Set values = type
Choose bookeh
Set cluster by to month
Open options dialog
Add month to keys
Note: data is still clustered, but UI shows None. Switch cluster by to month and you will see no change. Set it back to None and the chart will change...

**Comment by markwatsonatx** [comment]
I lied in the last repro step:

"Note: data is still clustered, but UI shows None. Switch cluster by to month and you will see no change. Set it back to None and the chart will change..."

You can't actually switch cluster by to month at this point because it is a key field. The behavior is still the same. The data is clustered by month, but UI says None. If you select another field to cluster by it will update. Then go back to None and it will not match the original chart.

**Comment by DTAIEB** [comment]
added an option validation to make sure cluster by and colors fields are not already in keyfields or valuefields as well as exists in the schema #229
