### ISSUE TITLE
display() bar chart: displays wrong labels and no data

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#213]
0.86 (not data set specific)

```
import pixiedust
df = pixiedust.sampleData(2)
display(df)
```

* Select chart _type_  `bar`
* Select _options_ > _keys_ : `transaction_date`
* Select _options_ > _values_ : `price`
* Select _options_ > _number of rows_ : `10`
* Select `bokeh` as _renderer_
* Select _show legend_

### Actual behavior

* City names are displayed in the legend
* No transaction dates are displayed on the X axis
* No price data points are displayed

**Comment by vabarbosa** [comment]
bokeh.charts appears to be plotting the values on a time series axis. if you zoom out on the graph you can actually see all the values. we will need to use the bokeh.plotting api instead to get better control. however, that work is not in the scope of 1.0 so for the time being a workaround (https://github.com/ibm-cds-labs/pixiedust/commit/5a67a38e3fd673fedc3d0d8d835248164e99d93f) has been put in place to address this issue.

**Comment by ptitzler** [comment]
Displays as expected in 1.0.
