### ISSUE TITLE
display() bar chart: legend and bar color issues

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#214]
0.86

```
import pixiedust
df = sqlContext.createDataFrame(
   [("MA", "Massachusetts", 6.794),
    ("NC", "North Carolina", 10.043),
    ("RI", "Rhode Island", 1.056),
    ("NY", "New York", 19.796),
    ("NH", "New Hampshire", 1.331),
    ("CT", "Connecticut", 3.59)],
   ["abbreviation", "state", "population (in mil)"])
display(df)
```

* Select chart _type_  `bar`
* Select _options_ > _keys_ : `abbreviation`
* Select _options_ > _values_ : `population...`
* Select _options_ > _number of rows_ : `10`
* Select `bokeh` as _renderer_
* Select _show legend_
* Grouping is NOT selected

### Actual behavior

* Each bar has a different color (should be the same)
* Legends lists the population numbers

### Steps to reproduce the behavior

**Comment by DTAIEB** [comment]
User error, same color happens only when there cluster by is triggered

**Comment by ptitzler** [comment]
How does that explain that the legend lists the population numbers???

**Comment by ptitzler** [comment]
Looking okay in 0.88.
