### ISSUE TITLE
Bokeh cluster by subplots does not work

### ISSUE THREAD

**Issue by markwatsonatx** [ibm-cds-labs/pixiedust#233]
As a user, I want to cluster my charts by subplots using Bokeh

### Expected behavior

Multiple plots are created.

### Actual behavior

Chart is grouped.

### Steps to reproduce the behavior

Use Boston Crime data
df = pixiedust.sampleData(7)
display(df)
Choose bar chart
Set keys = district
Set values = type
Choose bookeh
Set Cluster by to month
Choose subplots

Chart is actually grouped

**Comment by markwatsonatx** [comment]
I think it would be acceptable to just remove the subplot option for 1.0.

**Comment by jessmantaro** [comment]
This is a dupe of #192

**Comment by DTAIEB** [comment]
Bokeh charts have been reworked, all combination should now work.
PR #235
