### ISSUE TITLE
Unicode bug when converting from Pandas dataframe

### ISSUE THREAD

**Issue by benhuds** [ibm-cds-labs/pixiedust#234]
Unicode characters are not displaying correctly when I convert a Pandas dataframe to a Spark dataframe for visualization with PixieDust.  The specific character which is creating bugs in this dataset is the umlaut (¨).

### Steps to reproduce the behavior

Notebook with reproduction can be found [here](https://github.com/benhuds/craftbeer-data/blob/master/PixieDust%20Unicode%20Bug.ipynb).

To reproduce the error:
- use pandas to read csv
- do some basic operations to clean the data
- use `sqlContext.createDataFrame` to convert pandas dataframe to Spark dataframe
- display using pixiedust
- search for 'k' and you should see the bug: "Kölsch" shows up as "KÃ¶lsch."

Interesting note: when I import the raw csv data directly into PixieDust by using `pixiedust.sampleData`, the error does not appear when displaying the data.  The url is [here](https://raw.githubusercontent.com/benhuds/craftbeer-data/master/ca-data.csv).

**Comment by DTAIEB** [comment]
@benhuds I think you have an encoding problem. Can you try adding: encoding='utf-8' argument to pandas.read_csv?

**Comment by benhuds** [comment]
That did the trick, thank you.  I didn't think that would be the case, since the umlaut prints properly using pandas (directly in the Jupyter notebook) even without the encoding argument.
