### ISSUE TITLE
As a pixiedust user, I want to consume the documentation in notebooks

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#245]
The documentation https://ibm-cds-labs.github.io/pixiedust/use.html provides sample listings (e.g. in https://ibm-cds-labs.github.io/pixiedust/loaddata.html that illustrate the API usage. As  a user I might want to run through the samples ("explore them") without the need to manually copy and paste text from the HTML page.

**Comment by ptitzler** [comment]
One option is to do something like it was done here: http://datascience.ibm.com/blog/use-ibm-data-science-experience-to-read-and-write-data-stored-on-amazon-s3/
At the bottom there's a link to the notebook on GitHub https://github.com/charles2588/bluemixsparknotebooks/blob/master/Python/read_write_S3.ipynb

**Comment by bradnoble** [comment]
#249 may be related

**Comment by ptitzler** [comment]
Take a look at https://github.com/jakevdp/PythonDataScienceHandbook

**Comment by DTAIEB** [comment]
Status needed?

**Comment by ptitzler** [comment]
With the publication of https://apsportal.ibm.com/exchange/public/entry/view/5b000ed5abda694232eb5be84c3dd7c1 and installation of the corresponding notebooks in local deployments this can be considered as delivered.

**Comment by ptitzler** [comment]
On DSX [this notebook](https://apsportal.ibm.com/exchange/public/entry/view/5b000ed5abda694232eb5be84c3dd7c1) provides a complete introduction to the PD API. In local deployments the following notebooks are installed and can be used as an alternative to reading the documentation:

* PixieDust 1 - Easy Visualizations.ipynb
* PixieDust 2 - Working with External Data.ipynb
* PixieDust 3 - Scala and Python.ipynb
* PixieDust 4 - Add External Spark Packages.ipynb
* PixieDust 5 - Stash to Cloudant.ipynb
