### ISSUE TITLE
Enhancements to PixieDust Intro Notebooks

### ISSUE THREAD

**Issue by DTAIEB** [ibm-cds-labs/pixiedust#248]
As a new PixieDust User, I want to clear Intro Notebooks that quickly show me the value of PixieDust

Breakdown the Intro Notebook into multiple simpler notebooks:

**Part 1: Display**
Use simple Dataframes with hard-coded data that quickly demonstrate the display functionality. Provide more explanation in the markdown section, ask them to take a moment and play around the different charts and options. Also add a few lines at the top of the notebook explaining how to run a cell, how to restart the kernel, etc...

**Part 2: Sample Data**
Now that the user has had a first contact with Notebooks and PixieDust, use the sampleData functionality to show them more meaty datasets, and what they can do with it.
Note: There is another ticket that will update the installed to automatically install the csv connector library, so once done we should remove the part that asks the user to use the packageManager to do it.

**Part 3: Scala bridge**
Show the Scala bridge examples i.e. execute scala code, pass variable between Python and Scala and vice-versa

**Part 4: PackageManager**
Show the apis, start by using printAllPackages to display the list, then add graphframe package, then print the list again. Ends with create a simple graph from the sample data

**Part 5: Stash to Cloudant** 
Create a simple Dataframe, display some charts, and then let the user use the Stash to Cloudant menu:
   -Create a connection using credentials from Bluemix
   -Save data to cloudant

**Comment by bradnoble** [comment]
Would also like to add context to step 1, where we install the progress monitor. Could be something like, “notebooks don’t really do a good job of letting you know the status of the cell you’re running, so we added a progress monitor to notebooks through pixiedust, to give people a better sense of progress, even on the biggest jobs being done by spark…"

**Comment by bradnoble** [comment]
Also think we should have a ToC near the top that helps people understand where they are in the flow. Something like this:

This sample notebook provides you with an introduction to many features included in [PixieDust](https://ibm-cds-labs.github.io/pixiedust/). 

1. Welcome to the PixieDust display() API
1. [Load Sample Data to play with Spark Dataframes](#)
1. [Use the PixieDust PackageManager to add Spark packages to Python Notebooks](#)
1. [Use Scala & Python in the same notebook](#)
1. [Stash dataframes to data stores](#)
1. [Contribute](#)

**Comment by DTAIEB** [comment]
Intro notebooks for local and DSX have been delivered
