### ISSUE TITLE
Local Installer should automatically download the intro notebooks

### ISSUE THREAD

**Issue by DTAIEB** [ibm-cds-labs/pixiedust#250]
As a new user who's installing PixieDust locally, I want to have the intro notebooks automatically downloaded for me, and not have to download them myself from Github one by one.

**Comment by bradnoble** [comment]
Important to also note here that downloading notebooks from Github is _nowhere_ near as clean as downloading an app repo, so this enhancement will go a long way to making the first steps with PixieDust must simpler, without having to fumble with Github.

**Comment by DTAIEB** [comment]
Download the notebooks to $PIXIEDUST_HOME/notebooks from github if they are not already there. Also installer will display the command to launch jupyter notebook:

#####################################################################
#	Congratulations: Kernel Python with Pixiedust (Spark 1.6) was successfully created in /Users/dtaieb/Library/Jupyter/kernels/pythonwithpixiedustspark16
#	You can start the Notebook server with the following command:
#		jupyter notebook /Users/dtaieb/pixiedust/notebooks
#####################################################################

**Comment by DTAIEB** [comment]
Fixed in PR# #258
