### ISSUE TITLE
Image rendered by pixiedust is too big

### ISSUE THREAD

**Issue by yfphoon** [ibm-cds-labs/pixiedust#313]
As a `user`, I want to `control the size of the image` so that `I can see the whole graph on my screen` (Image rendered by pixiedust is too big)

### Expected behavior
Ability to specify the length and width of the chart, just like in Brunel

### Actual behavior
The size of the graph is so huge I can't see the whole image on my screen without scrolling

### Steps to reproduce the behavior
Do a stack bar chart or a grouped bar chart.

**Comment by MargrietGroenendijk** [comment]
Would it be possible to add a slide bar to the `options` menu where you can set the size from 0-100%

**Comment by DTAIEB** [comment]
Yes that's what I was thinking as well. We could have a slider with bounds of 50 to 100%. I would still like to preserve the 4/3 ratio, but I can definitely see cases where the data warrant a different one.

**Comment by vabarbosa** [comment]
changes submitted in commit https://github.com/ibm-cds-labs/pixiedust/commit/f39fb0c738efe86cfabfaf9ad338bcf0465c67fd which allows scaling of image from 50-100%

**Comment by yfphoon** [comment]
I see that this issue is closed, the the graph rendered by pixiedust-1.0.5 is still huge.  How do I control the size of the graph?  Can you please give me the sample syntax?   This is my code right now:

from pixiedust.display import *
display(data)

**Comment by vabarbosa** [comment]
@yfphoon there is a chartsize slider in the chart controls which can be used to resize the chart:

<img width="800" alt="screen shot 2017-05-29 at 8 56 08 am" src="https://cloud.githubusercontent.com/assets/13156555/26550818/80cb4e36-444d-11e7-9797-ad58d70f2b41.png">

and subsequent runs of that specific cell will retain your set chart size
