### ISSUE TITLE
I want to use pixiedust

### ISSUE THREAD

**Issue by aborruso** [ibm-cds-labs/pixiedust#315]
As a very normal, I want to use pixiedust

### Expected behavior
After installation, import and use it.

### Actual behavior
When I create new notebook, and run

    from pixiedust.display import *

I have `ImportError: No module named pixiedust.display`

In my kernel list I have:

     pythonwithpixiedustspark21    /home/.../jupyter/kernels/pythonwithpixiedustspark21

### Steps to reproduce the behavior

- create new pixiedusts python 2.7 notebook;
- import pixiedusts .

How to solve it?

**Comment by DTAIEB** [comment]
@aborruso you need to first `import pixiedust`
Once you do, you can directly use `display` api.

**Comment by aborruso** [comment]
Hi @DTAIEB, if I import it I have no module exists ... :(

**Comment by DTAIEB** [comment]
@aborruso It looks like the pixiedust module is not installed, but I'm not sure how it can be since you were able to use the `jupyter pixiedust install` command to create your kernel. 
In any case, you can try to reinstall pixiedust: `pip install pixiedust` and see if that solves your issue

**Comment by aborruso** [comment]
thank you
