### ISSUE TITLE
As a user, I want to be able to view all points plotted on a map without them being group into clusters at a high zoom level.

### ISSUE THREAD

**Issue by aklson-datascientist** [ibm-cds-labs/pixiedust#332]
### Expected behavior
I like how when the map first displays it zooms automatically into the area of interest, I would like an option to prevent PixieDust from clustering points together

### Actual behavior
PixieDust groups points in close proximity into clusters, and to view the individual points one has to zoom into the cluster.

### Steps to reproduce the behavior
I prepared a notebook where I show the plot that I generated in Folium and would like to replicate in PixieDust. You can download it via this <a href="https://bit.ly/FSwithPixieDust">link</a>.

**Comment by rajrsingh** [comment]
addressed in #327 by adding non-clustered map options
