### ISSUE TITLE
As a notebook developer, I want to use pixie dust with a non-local spark master so that I can utilize pixie dust on my organizations Spark cluster

### ISSUE THREAD

**Issue by kheuton** [ibm-cds-labs/pixiedust#357]
### Expected behavior
I want to create a new sc object that knows the url of my spark master

### Actual behavior
When you boot up a pixiedust kernel, the `sc` object already exists and has `sc.master` = `local[10]`

### Steps to reproduce the behavior
Just boot up a pixiedust kernel locally

I apologize if this isn't an issue, but I've read the documentation and checked the sourcecode, and there doesn't seem to be any configuration where I can change the `master` argument from `local[10]`. Am I missing something?

**Comment by rajrsingh** [comment]
I'm no Spark configuration expert, but I think this is unrelated to Pixiedust. Making sc point to a remote Spark would happen at the Jupyter kernel configuration stage and Pixiedust would just use it.

**Comment by kheuton** [comment]
Thanks for your reply. Isn't the jupyter kernel part of Pixiedust? Any idea where the kernel configuration happens? My normal workflow is to simply use the vanilla python 2.7 kernel, import pyspark, and create the `sc` in the notebook, pointing to whichever master I like

**Comment by rajrsingh** [comment]
Like I said, I definitely have no experience with this type of setup but this article might help: http://blog.ibmjstart.net/2016/06/24/using-remote-kernels-jupyter-notebook-server/

**Comment by kheuton** [comment]
Thanks, although it looks like that article is about running kernels remotely. I'm fine with a local kernel, I just want the `sc` object created by the Pixiedust kernel to point to a spark master that isn't local[10].

 I could probably patch it myself on a personal fork by editing this line:
https://github.com/ibm-cds-labs/pixiedust/blob/ec0d7c01bc8fc6f667e91a4649cc5afc65a313af/install/createKernel.py#L472

and changing `local[10]` to the URL of my spark master, but I feel like this is a pretty common use case and wonder if it wouldn't be a useful feature of Pixiedust.

**Comment by rajrsingh** [comment]
hoping @DTAIEB will chime in here and correct my mistakes...

**Comment by DTAIEB** [comment]
@kheuton I agree with @rajrsingh this is a kernel configuration issue and not a PixieDust issue. I think the confusion comes from the fact that PixieDust provides a local installer which configures a local Spark instance. This installer is only a convenience script to help users setup a local dev environment quickly. You can always customize the environment by editing the jupyter configuration files yourself e.g kernel.json. 
> Note: you can use the standard command `jupyter kernelspec list` to find out where the kernel.json is.
> I also recommend you google how to configure jupyter. e.g: https://gist.github.com/tsailiming/c1654e73f30ef34baf02
