### ISSUE TITLE
As a data scientist, I want to see Options dialog display type of chart selected so that I remember which chart was chosen. 

### ISSUE THREAD

**Issue by chetnawarade** [ibm-cds-labs/pixiedust#62]
### Expected behavior
When user clicks on Options dialog, display type of chart (or even type of renderer, optional though as it is seen on the right hand side) as the drop down of type of chart does not store last selected type of chart.

### Actual behavior
Options does not display type of chart, so it is difficult to remember most suitable aggregate, x and y values for the chart.

### Steps to reproduce the behavior
Select type of chart. Click Options button.

**Comment by vabarbosa** [comment]
chart type has been added to the title of the options dialog as well above the options area of the visualization.
https://github.com/ibm-cds-labs/pixiedust/commit/7cf677e86a152233b7704a32fbbb6b976a98cab4

**Comment by vabarbosa** [comment]
@chetnawarade please review, test, and close if satisfactory

**Comment by chetnawarade** [comment]
+1 thanks @vabarbosa
