### ISSUE TITLE
Download DataFrame as JSON is broken

### ISSUE THREAD

**Issue by DTAIEB** [ibm-cds-labs/pixiedust#7]
@vabarbosa : Get following error in the browser console:
main.min.js:23119 Couldn't process kernel message TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

**Comment by vabarbosa** [comment]
@DTAIEB do you have a specific dataframe that is failing? it seems to work for me (using v0.34)

**Comment by vabarbosa** [comment]
empty string ("") used in place of missing values when converting to JSON: https://github.com/ibm-cds-labs/pixiedust/commit/13deb7450a187ef48a0444c55b27cdaa939b68aa

**Comment by DTAIEB** [comment]
Files won't download when too many rows are selected, but I think this is a different issue. Closing this one as fixed
