### ISSUE TITLE
Pixiedust Zeppelin Support

### ISSUE THREAD

**Issue by ArslanSaleem** [ibm-cds-labs/pixiedust#80]
Hi,

I am working in Zeppelin, it has support to visualize that but its visualization is limited. Is it possible to add pixiedust to Zeppelin, i had tried to integrate it Zeppelin but when i call display(dataframe). It display the following:

`{"data": {"text/plain": "<IPython.core.display.HTML object>", "text/html": "\n<script>\n    //Marker 706ab2be\n    setTimeout(function(){\n        var cells=IPython.notebook.get_cells().filter(function(cell){\n            if(!cell.output_area || !cell.output_area.outputs){\n                return false;\n            }\n            return cell.output_area.outputs.filter(function(output){\n                if (output.output_type===\"display_data\"&&output.data&&output.data[\"text/html\"]){\n                    return output.data[\"text/html\"].includes(\"//Marker 706ab2be\")\n                }\n                return false;\n            }).length > 0;\n        });\n        if(cells.length>0){\n            var cell=cells[0];\n            var cellId=cell.cell_id;\n            var cellMetadata=cell._metadata.pixiedust;\n            //cell.output_area.clear_output(false, true);\n            var old_msg_id = cell.last_msg_id;\n            if (old_msg_id) {\n                cell.kernel.clear_callbacks_for_msg(old_msg_id);\n            }\n            var snifferOptions = [];\n            \n                snifferOptions.push({'nostore_bokeh':!!window.Bokeh})\n            \n            \n        \n    \n    !\nfunction() {\n    cellId = typeof cellId === \"undefined\" ? \"\" : cellId;\n    var curCell=IPython.notebook.get_cells().filter(function(cell){\n        return cell.cell_id==\"cellId\".replace(\"cellId\",cellId);\n    });\n    curCell=curCell.length>0?curCell[0]:null;\n    console.log(\"curCell\",curCell);\n    var startWallToWall;\n    //Resend the display command\n    var callbacks = {\n        shell : {\n            payload : {\n                set_next_input : function(payload){\n                    if (curCell){\n                        curCell._handle_set_next_input(payload);\n                    }\n                }\n            }\n        },\n        iopub:{\n            output:function(msg){\n                console.log(\"msg\", msg);\n                if (true){\n                    curCell.output_area.handle_output.apply(curCell.output_area, arguments);\n                    curCell.output_area.outputs=[];\n                    return;\n                }\n                var msg_type=msg.header.msg_type;\n                var content = msg.content;\n                var executionTime = $(\"#execution706ab2be\");\n                if(msg_type===\"stream\"){\n                    $('#wrapperHTML706ab2be').html(content.text);\n                }else if (msg_type===\"display_data\" || msg_type===\"execute_result\"){\n                    var html=null;\n                    if (!!content.data[\"text/html\"]){\n                        html=content.data[\"text/html\"];\n                    }else if (!!content.data[\"image/png\"]){\n                        html=html||\"\";\n                        html+=\"<img src='data:image/png;base64,\" +content.data[\"image/png\"]+\"'></img>\";\n                    }\n                                                    \n                    if (!!content.data[\"application/javascript\"]){\n                        try {\n                            eval(content.data[\"application/javascript\"]);\n                        } catch(err) {\n                            curCell.output_area.handle_output.apply(curCell.output_area, arguments);\n                        }                        \n                        return;\n                    }\n                    \n                    if (html){\n                        try{\n                            $('#wrapperHTML706ab2be').html(html);\n                        }catch(e){\n                            console.log(\"Invalid html output\", e, html);\n                            $('#wrapperHTML706ab2be').html( \"Invalid html output. <pre>\" \n                                + html.replace(/>/g,'&gt;').replace(/</g,'&lt;').replace(/\"/g,'&quot;') + \"<pre>\");\n                        }\n\n                        if(curCell&&curCell.output_area&&curCell.output_area.outputs){\n                            setTimeout(function(){\n                                var data = JSON.parse(JSON.stringify(content.data));\n                                if(!!data[\"text/html\"])data[\"text/html\"]=html;\n                                function savedData(data){\n                                    \n                                    var markup='<style type=\"text/css\">.pd_warning{display:none;}</style>';\n                                    markup+='<div class=\"pd_warning\"><em>Hey, there\\'s something awesome here! To see it, open this notebook outside GitHub, in a viewer like Jupyter</em></div>';\n                                    nodes = $.parseHTML(data[\"text/html\"], null, true);\n                                    var s = $(nodes).wrap(\"<div>\").parent().find(\".pd_save\").not(\".pd_save .pd_save\")\n                                    s.each(function(){\n                                        var found = false;\n                                        if ( $(this).attr(\"id\") ){\n                                            var n = $(\"#\" + $(this).attr(\"id\"));\n                                            if (n.length>0){\n                                                found=true;\n                                                n.each(function(){\n                                                    $(this).addClass(\"is-viewer-good\");\n                                                });\n                                                markup+=n.wrap(\"<div>\").parent().html();\n                                            }\n                                        }else{\n                                            $(this).addClass(\"is-viewer-good\");\n                                        }\n                                        if (!found){\n                                            markup+=$(this).parent().html();\n                                        }\n                                    });\n                                    data[\"text/html\"] = markup;\n                                    return data;\n                                }\n                                curCell.output_area.outputs.push({\"data\": savedData(data),\"metadata\":content.metadata,\"output_type\":msg_type});\n                            },2000);\n                        }\n                    }\n                }else if (msg_type === \"error\") {\n                    require(['base/js/utils'], function(utils) {\n                        var tb = content.traceback;\n                        console.log(\"tb\",tb);\n                        if (tb && tb.length>0){\n                            var data = tb.reduce(function(res, frame){return res+frame+'\\\\n';},\"\");\n                            console.log(\"data\",data);\n                            data = utils.fixConsole(data);\n                            data = utils.fixCarriageReturn(data);\n                            data = utils.autoLinkUrls(data);\n                            $('#wrapperHTML706ab2be').html(\"<pre>\" + data +\"</pre>\");\n                        }\n                    });\n                }\n\n                //Append profiling info\n                if (executionTime.length > 0 && $(\"#execution706ab2be\").length == 0 ){\n                    $('#wrapperHTML706ab2be').append(executionTime);\n                }else if (startWallToWall && $(\"#execution706ab2be\").length > 0 ){\n                    $(\"#execution706ab2be\").append($(\"<div/>\").text(\"Wall to Wall time: \" + ( (new Date().getTime() - startWallToWall)/1000 ) + \"s\"));\n                }\n            }\n        }\n    }\n    \n    if (IPython && IPython.notebook && IPython.notebook.session && IPython.notebook.session.kernel){\n        var command = \",cell_id='cellId'\".replace(\"cellId\",cellId);\n        function addOptions(options){\n            function getStringRep(v) {\n                return \"'\" + v + \"'\";\n            }\n            for (var key in (options||{})){\n                var value = options[key];\n                var hasValue = value != null && typeof value !== 'undefined' && value !== '';\n                var replaceValue = hasValue ? (key+\"=\" + getStringRep(value) ) : \"\";\n                var pattern = (hasValue?\"\":\",\")+\"\\\\s*\" + key + \"\\\\s*=\\\\s*'(\\\\\\\\'|[^'])*'\";\n                var rpattern=new RegExp(pattern);\n                var n = command.search(rpattern);\n                if ( n >= 0 ){\n                    command = command.replace(rpattern, replaceValue);\n                }else if (hasValue){\n                    var n = command.lastIndexOf(\")\");\n                    command = [command.slice(0, n), (command[n-1]==\"(\"? \"\":\",\") + replaceValue, command.slice(n)].join('')\n                }        \n            }\n        }\n        if(typeof cellMetadata != \"undefined\" && cellMetadata.displayParams){\n            addOptions(cellMetadata.displayParams);\n            addOptions({\"showchrome\":\"true\"});\n        }else if ('False'=='True' && curCell && curCell._metadata.pixiedust ){\n            addOptions(curCell._metadata.pixiedust.displayParams || {} );\n        }\n        addOptions({});\n        \n        \n        \n                for (var o in snifferOptions){\n                    addOptions(snifferOptions[o]);\n                }\n            \n    \n        var pattern = \"\\\\w*\\\\s*=\\\\s*'(\\\\\\\\'|[^'])*'\";\n        var rpattern=new RegExp(pattern,\"g\");\n        var n = command.match(rpattern);\n        var displayParams={}\n        for (var i = 0; i < n.length; i++){\n            var parts=n[i].split(\"=\");\n            var key = parts[0].trim();\n            var value = parts[1].trim()\n            if (!key.startsWith(\"nostore_\") && key != \"showchrome\" && key != \"prefix\" && key != \"cell_id\"){\n                displayParams[key] = value.substring(1,value.length-1);\n            }\n        }\n        if(curCell&&curCell.output_area){\n            curCell._metadata.pixiedust = curCell._metadata.pixiedust || {}\n            curCell._metadata.pixiedust.displayParams=displayParams\n            curCell.output_area.outputs=[];\n            var old_msg_id = curCell.last_msg_id;\n            if (old_msg_id) {\n                curCell.kernel.clear_callbacks_for_msg(old_msg_id);\n            }\n        }else{\n            console.log(\"couldn't find the cell\");\n        }\n        $('#wrapperJS706ab2be').html(\"\")\n        $('#wrapperHTML706ab2be').html('<div style=\"width:100px;height:60px;left:47%;position:relative\"><i class=\"fa fa-circle-o-notch fa-spin\" style=\"font-size:48px\"></i></div>'+\n        '<div style=\"text-align:center\">Loading your data. Please wait...</div>');\n        startWallToWall = new Date().getTime();\n        \n        console.log(\"Running command2\",command);\n        IPython.notebook.session.kernel.execute(command, callbacks, {silent:true,store_history:false,stop_on_error:true});\n    }\n}\n()\n        }else{\n            alert(\"An error occurred, unable to access cell id\");\n        }\n    },500);\n</script>"}, "metadata": {}}`

Any help related to this issue? Or anyone had tried pixiedust with Zeppelin?

**Comment by DTAIEB** [comment]
Hi @ArslanSaleem 
Unfortunately, PixieDust is currently only support Jupyter and there is no plan in the near future to work on a version for Zeppelin as the priority is to work on the backlog of the features we have identified. 
I'll close this issue for now, but feel free to keep sharing your feedback
