### ISSUE TITLE
pixiedust.sampleData(n) doesn't load any data on DSX

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/pixiedust#94]
I've tried several data sets using PD v0.80 on DSX.

```
in [6] pixiedust.sampleData(6)

Downloading 'Million dollar home sales in NE Mass late 2016' from https://openobjectstore.mybluemix.net/misc/milliondollarhomes.csv

Creating pySpark DataFrame for 'Million dollar home sales in NE Mass late 2016'. Please wait...
```

Even for a small data set like the one listed above (~100k) data frame creation never completes.

**Comment by vabarbosa** [comment]
works well for me on local. appears to have been a DSX issue. are you still experiencing the problem on DSX?

**Comment by ptitzler** [comment]
No, it's working today on DSX.
